"""Site models for /v1/sites/* (API.md §5).

Four endpoints:
- GET /v1/sites           -> SiteListResponse / SiteListItem
- GET /v1/sites/{icao}    -> SiteDetail (composes SiteWeather)
- GET /v1/sites/{icao}/sla -> SiteSla (composes SparklinePoint)
- GET /v1/sites/{icao}/{inbound,outbound} -> SiteFlightListResponse / FlightSummary

Shared Literals (FlightCategory, FlightStatus, SlaPeriod, WeatherImpact)
live in `models/common.py`.
"""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, Field

from app.models.common import FlightCategory, FlightStatus, SlaPeriod, WeatherImpact


class SiteListItem(BaseModel):
    """One row of GET /v1/sites."""

    icao: str = Field(description="4-char ICAO identifier (e.g. 'KSFO').")
    iata: str | None = Field(description="3-char IATA code if assigned (e.g. 'SFO').")
    name: str = Field(description="Airport name from the FAA registry.")
    state: str = Field(description="2-char US state postal abbreviation.")
    customer_regions: list[str] = Field(
        description="Customer regions this site covers (subset of {west, east, all})."
    )
    is_in_scope: bool = Field(
        description="True if the caller's Scope grants read access to this site."
    )


class SiteListResponse(BaseModel):
    """Response for GET /v1/sites."""

    items: list[SiteListItem] = Field(description="One entry per watched airport.")
    count: int = Field(description="Length of `items`.")


class SiteWeather(BaseModel):
    """Weather attached to a SiteDetail.

    Sourced from app.airport_conditions (refreshed every 5 min by the
    noaa_weather asset).
    """

    metar_raw: str = Field(description="Raw METAR text as published by the station.")
    metar_plain_english: str | None = Field(
        description=(
            "Plain-English METAR translation generated by Anthropic Claude and "
            "cached. Always null in v1 — the LLM-summarization asset lands in a "
            "later phase."
        )
    )
    flight_category: FlightCategory = Field(
        description="FAA flight category derived from ceiling + visibility."
    )
    wind_kt: int | None = Field(description="Wind speed in knots, null if calm or unreported.")
    visibility_sm: float | None = Field(description="Prevailing visibility in statute miles.")
    ceiling_ft: int | None = Field(
        description="Ceiling above ground in feet. Null when CAVU (no ceiling layer)."
    )
    observed_at: datetime = Field(description="UTC timestamp of the METAR observation.")


class SiteDetail(BaseModel):
    """Response for GET /v1/sites/{icao}."""

    icao: str = Field(description="4-char ICAO identifier.")
    iata: str | None = Field(description="3-char IATA code if assigned.")
    name: str = Field(description="Airport name from the FAA registry.")
    city: str | None = Field(description="Nearest associated city.")
    state: str = Field(description="2-char US state postal abbreviation.")
    lat: float = Field(ge=-90, le=90, description="Latitude in decimal degrees (WGS84).")
    lon: float = Field(ge=-180, le=180, description="Longitude in decimal degrees (WGS84).")
    elevation_ft: int | None = Field(description="Field elevation above MSL in feet.")
    timezone: str = Field(
        description=(
            "IANA timezone (e.g. 'America/Los_Angeles'). Always null in v1 — "
            "ref.airports.timezone backfill lands in a later phase."
        )
    )
    weather: SiteWeather | None = Field(
        description="Most recent weather observation, or null if the station hasn't reported."
    )
    inbound_count_60m: int = Field(description="Aircraft inbound within the next 60 minutes.")
    outbound_count_60m: int = Field(
        description="Aircraft that departed within the last 60 minutes."
    )
    active_case_count: int = Field(
        description="Open AFM cases against this site. Always 0 until Phase 05."
    )
    customer_regions: list[str] = Field(
        description="Customer regions this site covers (subset of {west, east, all})."
    )


class SparklinePoint(BaseModel):
    """One day of an SLA scorecard's 7-day trend line."""

    day: date = Field(description="Calendar day this point represents (UTC).")
    on_time_pct: float | None = Field(
        description="On-time percentage for that day (0-100). Null until Phase 05."
    )
    avg_delay_min: float | None = Field(
        description="Average delay in minutes for that day. Null until Phase 05."
    )


class SiteSla(BaseModel):
    """Response for GET /v1/sites/{icao}/sla.

    All SLA metric fields return null/0 in Phase 02 — the SLA pipeline
    lands in Phase 05. The endpoint shape is locked now so the dashboard
    can render the scorecard with placeholders.
    """

    icao: str = Field(description="4-char ICAO identifier.")
    period: SlaPeriod = Field(description="Aggregation window (echoed from the query param).")
    inbound_count: int = Field(description="Inbound arrivals in `period`. Always 0 until Phase 05.")
    outbound_count: int = Field(
        description="Outbound departures in `period`. Always 0 until Phase 05."
    )
    on_time_arrival_pct: float | None = Field(
        description="Arrival on-time percentage (0-100). Null until Phase 05."
    )
    on_time_departure_pct: float | None = Field(
        description="Departure on-time percentage (0-100). Null until Phase 05."
    )
    avg_arrival_delay_min: float | None = Field(
        description="Average arrival delay in minutes. Null until Phase 05."
    )
    avg_departure_delay_min: float | None = Field(
        description="Average departure delay in minutes. Null until Phase 05."
    )
    weather_impact: WeatherImpact = Field(
        description=(
            "Qualitative weather-impact bucket. In v1 this is derived from the "
            "current flight_category (LIFR -> high, IFR -> medium, otherwise low)."
        )
    )
    flight_category: FlightCategory = Field(description="Current FAA flight category at this site.")
    active_cases: int = Field(description="Open AFM cases. Always 0 until Phase 05.")
    sparkline_7d: list[SparklinePoint] = Field(
        description="Seven daily points for trend rendering. Empty list in v1."
    )


class FlightSummary(BaseModel):
    """One row of GET /v1/sites/{icao}/{inbound,outbound}.

    `origin_icao`, `destination_icao`, `eta_minutes`, and `status` (other
    than 'unknown') depend on the flight-plan asset deferred from Phase
    01. They surface here as documented nulls / 'unknown' until that
    lands.
    """

    icao24: str = Field(description="Lowercase 24-bit ICAO transponder address.")
    callsign: str | None = Field(description="Mode S callsign.")
    origin_icao: str | None = Field(
        description="Departure airport ICAO. Null in v1 (no flight-plan asset)."
    )
    destination_icao: str | None = Field(
        description="Arrival airport ICAO. Null in v1 (no flight-plan asset)."
    )
    eta_minutes: int | None = Field(description="Estimated minutes to destination. Null in v1.")
    status: FlightStatus = Field(
        description=(
            "Flight lifecycle status. Always 'unknown' in v1 until the "
            "case-detector pipeline lands."
        )
    )
    aircraft_type: str | None = Field(description="ICAO type code (e.g. 'B738') from the registry.")


class SiteFlightListResponse(BaseModel):
    """Response for GET /v1/sites/{icao}/{inbound,outbound}."""

    items: list[FlightSummary] = Field(description="One entry per matching aircraft.")
    count: int = Field(description="Length of `items`.")
