#!/usr/bin/env bash
#
# Seed the runbook reference Files (ContentVersion) into the Salesforce org.
#
# Each runbooks/*.md becomes a ContentDocument whose Title matches the matching
# AFM_Runbook__mdt.Title__c. That Title is the join key AFM_CaseTriageService
# (Group B) uses to link the runbook File to a Case via ContentDocumentLink.
# PathOnClient is set to "<runbook-id>.md" for traceability back to the source.
#
# Idempotent: any existing File whose Title is one of the eight runbook titles
# is deleted first, so a re-run fully refreshes content. NOTE this also removes
# any ContentDocumentLinks to those Files — links are re-created on the next
# triage run, so only re-seed when no live Case links matter.
#
# Usage:
#   scripts/seed_runbook_files.sh [target-org-alias]   # default: afm-dev
#
set -euo pipefail

ORG="${1:-${SF_TARGET_ORG:-afm-dev}}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNBOOK_DIR="$REPO_ROOT/runbooks"

if [[ ! -d "$RUNBOOK_DIR" ]] || ! compgen -G "$RUNBOOK_DIR/*.md" > /dev/null; then
  echo "error: no runbook markdown found in $RUNBOOK_DIR" >&2
  exit 1
fi

APEX_FILE="$(mktemp --suffix=.apex)"
trap 'rm -f "$APEX_FILE"' EXIT

# --- Build the anonymous Apex: collect ContentVersions, then delete-old + insert.
{
  echo "// Auto-generated by scripts/seed_runbook_files.sh — do not edit by hand."
  echo "List<ContentVersion> cvs = new List<ContentVersion>();"
} > "$APEX_FILE"

titles=()
count=0
for md in "$RUNBOOK_DIR"/*.md; do
  id="$(basename "$md" .md)"
  title="$(grep -m1 '^title:' "$md" | sed -E 's/^title:[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/')"
  if [[ -z "$title" ]]; then
    echo "error: no 'title:' frontmatter in $md" >&2
    exit 1
  fi
  esc_title="${title//\'/\\\'}"   # escape single quotes for the Apex string literal
  b64="$(base64 -w0 "$md")"
  titles+=("$esc_title")
  count=$((count + 1))
  {
    echo "cvs.add(new ContentVersion("
    echo "    Title = '${esc_title}',"
    echo "    PathOnClient = '${id}.md',"
    echo "    VersionData = EncodingUtil.base64Decode('${b64}')));"
  } >> "$APEX_FILE"
done

{
  printf 'Set<String> seedTitles = new Set<String>{'
  printf "'%s'," "${titles[@]}" | sed 's/,$//'
  printf '};\n'
  echo "List<ContentDocument> old = [SELECT Id FROM ContentDocument WHERE Title IN :seedTitles];"
  echo "if (!old.isEmpty()) { delete old; }"
  echo "insert cvs;"
  echo "System.debug(LoggingLevel.INFO, 'Seeded ' + cvs.size() + ' runbook ContentVersions.');"
} >> "$APEX_FILE"

echo "Seeding ${count} runbook Files into org '${ORG}'..."
sf apex run --target-org "$ORG" --file "$APEX_FILE"
echo "Done. Verify with: sf data query -o ${ORG} -q \"SELECT Title, FileExtension FROM ContentDocument WHERE Title IN ('${titles[0]}', ...)\""
